import {Contact} from '@app/entities/contact.entities';

export const fakeData: Array<Contact> = [
  {
    id: '1',
    firstName: 'Vu Huy Hieu',
    middleName: '',
    lastName: '',
    title: 'Project Manager',
    company: 'Sotatek',
    email: 'hieu.vh301195@gmail.com',
    phoneNumber: '0982960442',
    linkedIn: 'https://www.linkedin.com/in/vu-huy-hieu-301195/',
  },
  {
    id: '2',
    firstName: 'Vu Van Su',
    middleName: '',
    lastName: '',
    title: 'Mobile Dev',
    company: 'Sotatek',
    email: 'su.vu@gmail.com',
    phoneNumber: '0982553556',
    linkedIn: 'https://www.linkedin.com/in/su-vu-020598/',
  },
  {
    id: '3',
    firstName: 'Bui Chien Thang',
    middleName: '',
    lastName: '',
    title: 'Mobile Dev',
    company: 'Sotatek',
    email: 'thang.bui@gmail.com',
    phoneNumber: '0982687458',
    linkedIn: 'https://www.linkedin.com/in/thang-bui/',
  },
  {
    id: '4',
    firstName: 'Le Van Son',
    middleName: '',
    lastName: '',
    title: 'Mobile Dev',
    company: 'Sotatek',
    email: 'son.le@gmail.com',
    phoneNumber: '0982987654',
    linkedIn: 'https://www.linkedin.com/son-le',
  },
  {
    id: '5',
    firstName: 'Dao Thi Hue',
    middleName: '',
    lastName: '',
    title: 'tester',
    company: 'Sotatek',
    email: 'hue.dao@gmail.com',
    phoneNumber: '0982655556',
    linkedIn: 'https://www.linkedin.com/in/hue-dao/',
  },
];
